### PR TITLE
add new cp2k revision

### PR DESCRIPTION
**Pull request by edditler**
We need to urgently switch cp2k versions because of a DFT-D3 bug.

### CODE REVIEW

**Comment by ltalirz** [comment]
Have you informed CSCS about this?
This pull request would mean that all Materialscloud users use your personal version (keimre's) of cp2k.
It would be preferable, if you could get them to compile an updated version. They are usually very responsive.

**Comment by edditler** [comment]
Since the version and revision number are still in the path they would need to be changed when CSCS compiles the new version. Further the data directory until now pointed to the private directory of schuetto, so we don't completely rely on the CSCS version anyways.

What would the upside of waiting be?

**Comment by cpignedoli** [comment]
OK I wrote to Luca Marsella to ask him to make available the cp2k temporary module

**Comment by ltalirz** [comment]
@edditler 
Well, it would mainly mean that keimre becomes responsible for maintaining cp2k@cscs for everyone on materialscloud

Note that of course you can immediately add your own cp2k version in your environment using `verdi code setup` - no need to wait

**Comment by cpignedoli** [comment]
so the 5.1 is now available

Ciao Carlo,

grazie per il messaggio, stavo per risponderti nel ticket. Abbiamo installato CP2K 5.1 su GPU e MC come non default, per cui ora vedi i moduli seguenti con “module avail CP2K”:

$ module avail CP2K
------------------------------ /apps/daint/UES/jenkins/6.0.UP04/gpu/easybuild/modules/all ------------------------------
CP2K/5.0r18043-CrayGNU-17.08-cuda-8.0(default) CP2K/5.1-CrayGNU-17.08-cuda-8.0


So yes this should be the policy probably:
in the materials cloud we keep "a standard CSCS module path"
(who will be in charge to keep this up-to-date?)
and for personal modifications we act at the verdi commandline level

Is this what you suggest Leo?

We should soon meet do update strategies

**Comment by ltalirz** [comment]
I hope you gave them good marks in the CSCS user survey!

But wait - now I'm confused... The r18043 is shown as default...
Edit: Ok, it's indeed the old version.

**Comment by edditler** [comment]
I amended the pull request to point to the new version by CSCS.

**Comment by oschuett** [comment]
While you're talking to CSCS, maybe yo can also convince them to support the DATA_DIR.

**Comment by ltalirz** [comment]
@cpignedoli Any news concerning the DATA_DIR?
If not, I'll approve the pull request now and kindly ask @edditler to make another one once this is available.

**Comment by cpignedoli** [comment]
Luca told me he would have replied me in the ticket. he still did not.

Today Edward is not here so we can wait till tomorrow

**Comment by cpignedoli** [comment]
Dear Carlo,

as discussed, I have created new CP2K modulefiles on Piz Daint (one for the gpu and another one for the mc software stack), based on the last stable version 5.1 available for download on www.cp2k.org:

$ module load daint mc
$ module avail CP2K
------------------------------ /apps/daint/UES/jenkins/6.0.UP04/mc/easybuild/modules/all -------------------------------
CP2K/5.0r18043-CrayGNU-17.08(default) CP2K/5.1-CrayGNU-17.08

$ module switch daint-mc daint-gpu
$ module avail CP2K
------------------------------ /apps/daint/UES/jenkins/6.0.UP04/gpu/easybuild/modules/all ------------------------------
CP2K/5.0r18043-CrayGNU-17.08-cuda-8.0(default) CP2K/5.1-CrayGNU-17.08-cuda-8.0

The new modules are not yet default, but we plan to announce the change of the default after the next maintenance on Feb 22nd.

I have followed your request and inserted the "data" folder with basis sets and pseudo potentials in the installation folder: the environment variable "CP2K_DATA_DIR" defined in the modulefile points to that folder and allows the executable to find the data sets. 

I have also added the "arch" folder with the "arch" file used to build the corresponding executable, together with the "tests" folder which I have used to check that the executable "cp2k.psmp" was working as expected.

Please let me know if you can use the new executables correctly.

Ciao,
Luca

**Comment by ltalirz** [comment]
@edditler Happy to approve, when the appropriate data dir path has been added.
If they provided the path at compile time, the prepend text might not even be necessary.

**Comment by ltalirz** [comment]
I've checked the path, apart from this I'll assume it works :)

**Pull request merged**
